version: '2'

services:
  master:
    build:
      context: master
      dockerfile: Dockerfile
      args:
        PORT: 7001
    network_mode: "host"

  slave1:
    build:
      context: slave1
      dockerfile: Dockerfile
      args:
        PORT: 7002
    network_mode: "host"

  slave2:
    build:
      context: slave2
      dockerfile: Dockerfile
      args:
        PORT: 7003
    network_mode: "host"

  sentinel1:
    build: 
      context: sentinel1
      dockerfile: Dockerfile
      args:
        PORT: 7004
    network_mode: "host"

  sentinel2:
    build: 
      context: sentinel2
      dockerfile: Dockerfile
      args:
        PORT: 7005
    network_mode: "host"

  sentinel3:
    build:
      context: sentinel3
      dockerfile: Dockerfile
      args:
        PORT: 7006
    network_mode: "host"

